"""add_salary_and_shift_to_staff

Revision ID: fc1e43d78913
Revises: 4fe4f2f4115a
Create Date: 2026-05-26 13:42:36.308587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc1e43d78913'
down_revision: Union[str, Sequence[str], None] = '4fe4f2f4115a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('salary', sa.Float(), nullable=True))
    op.add_column('staff', sa.Column('shift_time', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'shift_time')
    op.drop_column('staff', 'salary')
    # ### end Alembic commands ###
